### ISSUE TITLE
I created a plug -in to add a Fernflower compiler, but it does not work. Please help see why

### ISSUE THREAD

**Issue by meiMingle** [Recaf-Plugins/Recaf-4x-plugin-workspace#1]
@Col-E This is my source code
https://github.com/meiMingle/fernflower-recaf-plugin

**Comment by Col-E** [comment]
Apply these patches: [changes.patch](https://github.com/user-attachments/files/17609195/changes.patch)

![image](https://github.com/user-attachments/assets/663a9611-0a8f-4306-a51a-56689a5b3480)

**Comment by meiMingle** [comment]
Thanks to my friend @Col-E , now there is another problem. I added the file 'resources/translations/en_US.lang', which makes the current plugin configuration display correctly, but breaks the configuration display of the entire Recaf except this one. 
![image](https://github.com/user-attachments/assets/c0ac35f7-2123-4e9a-900b-4f86e98d186d)
